# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=false

# Ballistix parameters
mod_version=0.9.4-1
mod_id=ballistix
mod_group_id=ballistix
mod_name=Ballistix

#Other Parameters
mod_license=All Rights Reserved
mod_authors=aurilisdev, skip999
mod_credits=Thanks to all contributors. Brazil lang key by FITFC. Russian lang key by Quarkrus
mod_description=A continuation of ICBM expanding on its core principles with a unique spin

# Version parameters
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.72
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)


# Dependency parameters
jei_version=19.21.0.246

# Parchment parameters
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28
